
###
POST {{host}}/users/register
Content-Type: application/json

{
  "email": "diory3@gmail.com",
  "username": "diory3",
  "password": "Diory123?"
}

###
POST {{host}}/users/login
Content-Type: application/json

{
  "email": "diory3@gmail.com",
  "password": "Diory123?"
}

###
GET {{host}}/reflections
Authorization: Bearer {{token}}

###
POST {{host}}/reflections
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "success":"today success 2",
  "low_point":"new low point user 3",
  "take_away":"new Take Away user 3"
}

###
PUT {{host}}/reflections/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "success": "today success"
}

###
DELETE {{host}}/reflections/5
Authorization: Bearer {{token}}
