
###
POST {{host}}/users/register
Content-Type: application/json

{
  "email": "diory4@gmail.com",
  "username": "diory2",
  "password": "Diory123?"
}

###
POST {{host}}/users/login
Content-Type: application/json

{
  "email": "diory1@gmail.com",
  "password": "12345"
}

###
GET {{host}}/reflections
Authorization: Bearer {{accessToken}}

###
POST {{host}}/reflections
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "success":"today success",
  "low_point":"new low point user 3",
  "take_away":"new Take Away user 3"
}

###
PUT {{host}}/reflections/12
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "success":"today Not success",
  "low_point":"new low point new user 3",
  "take_away":"new Take Away new user 3"
}

###
DELETE {{host}}/reflections/6
Authorization: Bearer {{accessToken}}
